### ISSUE TITLE
move to freifunk-potsdam

### ISSUE THREAD

**Issue by niccokunzmann** [seth0r/ffp-monitor#2]
Hi, du kannst es unter Settings -> runterscrollen -> Transfer nach Freifunk-Potsdam verschieben.

Discussion: https://lists.freifunk-potsdam.de/pipermail/users/2019-March/018695.html

In der Berliner Mailingliste wurde auch schonmal diskutiert, was man nutzen kann. Ich denke, diese Implementierung ist eine Beitrag.

**Comment by seth0r** [comment]
ist umgezogen
